UPSC_SYLLABUS_SEEDS = {
    "Polity & Governance": [
        "Constitutional amendments procedure and basic structure doctrine",
        "Judicial review public interest litigation and judicial activism",
        "Emergency provisions article 356 and center state administrative friction",
        "Statutory regulatory and quasi judicial bodies composition and powers",
        "Representation of people act disqualification of mps and mlas",
        "Fifth and sixth schedule areas tribal governance and autonomous councils",
        "Fundamental rights article 14 19 21 and reasonable restrictions",
        "Directive principles of state policy and fundamental duties",
        "Parliamentary committees and legislative procedure",
        "Federalism centre state relations and interstate council",
        "Election commission of india powers and electoral reforms",
        "Union budget and parliamentary financial control",
        "Supreme court high court jurisdiction and writ jurisdiction",
        "Anti defection law and tenth schedule",
        "Local self government panchayati raj and municipalities",
        "National human rights commission and other statutory bodies",
        "Official language and linguistic reorganization of states",
        "Citizenship acquisition termination and overseas citizen of india",
        "Tribunals and alternative dispute resolution mechanisms",
        "Right to information act and transparency in governance",
    ],
    "Economy": [
        "Fiscal policy deficit financing and fiscal responsibility management frbm",
        "Monetary policy committee inflation targeting and liquidity adjustment facility",
        "Banking sector reforms non performing assets npa and insolvency bankruptcy code",
        "Subsidies direct benefit transfer dbt and public distribution system reforms",
        "External sector capital account convertibility and foreign direct investment policy",
        "Gst council composition and indirect tax reforms",
        "Agriculture msp procurement and pds reforms",
        "Financial inclusion jan dhan aadhaar mobile jAM trinity",
        "Securities market sebi regulations and ipo reforms",
        "Labour codes and social security reforms 2020",
        "Disinvestment and public sector enterprise policy",
        "Insurance penetration and irda regulations",
        "International financial institutions imf world bank adb",
        "Trade policy wto disputes and free trade agreements",
        "Digital currency central bank digital currency and crypto regulation",
        "National monetisation pipeline and asset monetisation",
        "Production linked incentive pli schemes and manufacturing",
        "Startup india and ease of doing business rankings",
        "Multidimensional poverty index and sustainable development goals",
        "National infrastructure pipeline and gatishakti masterplan",
    ],
    "Environment & Geography": [
        "UNFCCC climate commitments cop Paris agreement and carbon markets",
        "Wildlife protection act schedules and national board for wildlife mandates",
        "Environmental impact assessment eia process and draft notifications",
        "Biodiversity conservation convention on biological diversity cbd protocols",
        "Monsoon mechanisms El Nino southern oscillation enso and Indian ocean dipole",
        "National action plan on climate change and state action plans",
        "Forest rights act and tribal forest governance",
        "Wetlands conservation and ramsar sites in india",
        "Air quality index and national clean air programme",
        "Coastal regulation zone and mangrove conservation",
        "Indian desert thar and western ghats ecology",
        "Himalayan glacier dynamics and river systems",
        "Disaster management act and national disaster response force",
        "Nuclear energy three stage programme and safety regulations",
        "Renewable energy targets solar wind and green hydrogen mission",
        "Waste management rules solid e waste plastic and biomedical",
        "Interlinking of rivers and national water policy",
        "Ocean resources blue economy and deep sea mining",
        "Drought prone area programme and watershed management",
        "Climate resilient agriculture and crop insurance schemes",
    ],
    "Science & Technology": [
        "Three stage nuclear power program and pressurized heavy water reactors",
        "ISRO launch vehicles pslv gslv and reusable launch technology payloads",
        "Intellectual property rights ipr patent amendments and compulsory licensing",
        "Biotechnology applications crispr cas9 gene editing and biosafety regulations",
        "Quantum computing and national quantum mission",
        "Artificial intelligence governance and national ai strategy",
        "Cybersecurity national cyber security policy and data protection",
        "5g technology deployment and telecommunications reforms",
        "Nanotechnology applications in medicine and materials",
        "Space exploration chandrayaan mangalyaan and aditya l1",
        "Hydrogen fuel cell technology and green hydrogen standards",
        "Electric vehicle policy and battery manufacturing in india",
        "Genome india project and indian genetic diversity mapping",
        "Deep ocean mission and samudrayaan project",
        "Semiconductor manufacturing and chip design policy",
        "Blockchain technology and its applications in governance",
        "Internet governance net neutrality and digital divide",
        "India's human spaceflight program gaganyaan",
        "MRNA vaccine technology and pandemic preparedness",
        "National supercomputing mission and computational research",
    ],
    "International Relations": [
        "India us comprehensive global strategic partnership and i2u2",
        "India china border disputes and military de escalation mechanisms",
        "India pakistan relations cross border terrorism and trade",
        "India russia strategic partnership and defense procurement",
        "Neighbourhood first policy saarc bimstec and connectivity projects",
        "Indo pacific outlook and quad cooperation",
        "India eu trade relations and free trade agreement negotiations",
        "Act east policy and asean india strategic partnership",
        "India central asia connectivity and chabahar port development",
        "India africa forum summit and development cooperation",
        "India gulf region diaspora and energy security",
        "United nations security council reforms and india's candidature",
        "Nuclear nonproliferation treaty and nsg membership",
        "Climate finance loss and damage fund and cbdr principles",
        "International solar alliance and coalition for disaster resilient infrastructure",
        "India's development partnership and lines of credit to africa",
        "Maritime security indian ocean rim association and piracy",
        "India west asia relations israel palestine and energy corridor",
        "World trade organization dispute settlement and fisheries subsidies",
        "Global south voice and india's g20 presidency outcomes",
    ],
    "Social & Culture": [
        "Scheduled castes scheduled tribes and reservation policy",
        "National education policy 2020 and school curriculum reforms",
        "Women empowerment and reservation of women in parliament",
        "Child labour prohibition and right to education act",
        "Ayushman Bharat and universal health coverage",
        "Poshan abhiyan and nutritional security for children",
        "National health mission and disease surveillance",
        "Mental healthcare act and suicide decriminalization",
        "Transgender rights and transgender persons act",
        "Senior citizens welfare and maintenance of parents act",
        "Drug abuse control and narcotics regulation",
        "Vaccination policy universal immunization programme and covid19 management",
        "Right to food national food security act and mid day meal",
        "Mgnrega and rural employment guarantee",
        "Migration and urban housing policies",
        "Tribal welfare schemes and particularly vulnerable tribal groups",
        "Intangible cultural heritage unesco inscriptions from india",
        "Classical dance forms and folk traditions of india",
        "Sanskrit revival and traditional knowledge protection",
        "Museums and cultural infrastructure development",
    ],
}


def get_flattened_syllabus_seeds():
    flattened = []
    for subject, topics in UPSC_SYLLABUS_SEEDS.items():
        flattened.extend(topics)
    return flattened


def get_subject_for_seed(seed_index: int, flattened: list[str] | None = None) -> str:
    if flattened is None:
        flattened = get_flattened_syllabus_seeds()
    cul_sum = 0
    for subject, topics in UPSC_SYLLABUS_SEEDS.items():
        cul_sum += len(topics)
        if seed_index < cul_sum:
            return subject
    return "GS"
